### PR TITLE
Update dqflags_jwst.txt

### PR DESCRIPTION
**Pull request by marcio-melendez**
Updated JWST quality flags from:
 https://jwst-pipeline.readthedocs.io/en/latest/jwst/references_general/references_general.html#data-quality-flags

### CODE REVIEW

**Comment by pllim** [comment]
Thank you! Just to make sure, did you try using `stginga` with this patch on your JWST images and see if `DQInspect` still work as expected?

**Comment by marcio-melendez** [comment]
It did not work as expected. The file itself with the appropriate DQ flags is Ok but it seems that DQInspect is not setup correctly to read from the different files (different instruments) because the DQ flags are set by default at the beginning.

**Comment by pllim** [comment]
@obi-wan76 , the data file should have overwritten the default settings. Did you "install" a `~/.ginga/plugin_DQInspect.cfg` as stated in https://stginga.readthedocs.io/en/stable/stginga/plugins_manual/dqinspect.html ?

**Comment by marcio-melendez** [comment]
@pllim This is what I did:
1. From the stginga/examples folder I copied the file plugin_DQInspect.cfg file into $HOME/.ginga 
2. Then, I copied the file dqflags_jwst.txt (with the correct DQ definitions)  into the stginga data folder (inside my conda evn for stginga). 
3. I run stginga directly so it load the plugins 

Now, when running on the terminal I noticed the following errors:

```
Error importing Ginga config file: 'GingaShell' object has no attribute 'local_plugins'
Traceback:
  File "/Users/melendez/anaconda3/envs/astroconda2020/lib/python3.6/site-packages/ginga/rv/main.py", line 478, in main
    ginga_config.pre_gui_config(ginga_shell)

  File "/Users/melendez/.ginga/ginga_config.py", line 3, in pre_gui_config
    load_plugins(ginga)

  File "/Users/melendez/anaconda3/envs/astroconda2020/lib/python3.6/site-packages/stginga/plugin_info.py", line 33, in load_plugins
    if lplg['module'] in ginga.local_plugins:
```

**Review by pllim — APPROVED** [review]
There were 3 problems:

1. `entry_points` was broken -- fixed in 61a3811a9d5a7551e22cde6cf61d07aef41c9b27
2. Non-ASCII quotes in `dqflags_jwst.txt` -- fixed here
3. User-side `~/.ginga/general.cfg` needs to have the following setting

https://github.com/spacetelescope/stginga/blob/61a3811a9d5a7551e22cde6cf61d07aef41c9b27/stginga/examples/configs/general.cfg#L52

I pushed a follow-up commit to this PR and tested it locally with user-provided JWST file and an existing HST/ACS file.
